/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 23:23:44 GMT 2022
 */

package dimacs9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dimacs9.DataHandler;
import dimacs9.Settings;
import org.junit.runner.RunWith;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DataHandler_ESTest extends DataHandler_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test0()  throws Throwable  {
      DataHandler dataHandler0 = null;
      try {
        dataHandler0 = new DataHandler((Settings) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dimacs9.DataHandler", e);
      }
  }
}
