/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 23:28:07 GMT 2022
 */

package dimacs9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dimacs9.DukqstraTime;
import dimacs9.PulseGraph;
import org.junit.runner.RunWith;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DukqstraTime_ESTest extends DukqstraTime_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test0()  throws Throwable  {
      DukqstraTime dukqstraTime0 = null;
      try {
        dukqstraTime0 = new DukqstraTime((PulseGraph) null, (-790));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dimacs9.DukqstraTime", e);
      }
  }

  @Test(timeout = 11000)
  public void test1()  throws Throwable  {
      PulseGraph pulseGraph0 = new PulseGraph(2610);
      DukqstraTime dukqstraTime0 = null;
      try {
        dukqstraTime0 = new DukqstraTime(pulseGraph0, (-1));
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("dimacs9.DukqstraTime", e);
      }
  }
}
