/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 23:27:02 GMT 2022
 */

package dimacs9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dimacs9.DukqstraDist;
import dimacs9.PulseGraph;
import org.junit.runner.RunWith;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DukqstraDist_ESTest extends DukqstraDist_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test0()  throws Throwable  {
      DukqstraDist dukqstraDist0 = null;
      try {
        dukqstraDist0 = new DukqstraDist((PulseGraph) null, (-967));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dimacs9.DukqstraDist", e);
      }
  }

  @Test(timeout = 11000)
  public void test1()  throws Throwable  {
      PulseGraph pulseGraph0 = new PulseGraph(246);
      DukqstraDist dukqstraDist0 = null;
      try {
        dukqstraDist0 = new DukqstraDist(pulseGraph0, 246);
        fail("Expecting exception: ArithmeticException");
      
      } catch(ArithmeticException e) {
         //
         // / by zero
         //
         verifyException("dimacs9.DukqstraDist", e);
      }
  }
}
