/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 23:30:33 GMT 2022
 */

package dimacs9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dimacs9.PulseMain;
import java.io.FileNotFoundException;
import java.io.IOException;
import org.junit.runner.RunWith;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PulseMain_ESTest extends PulseMain_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[1];
      try { 
        PulseMain.main(stringArray0);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileInputStream", e);
      }
  }

  @Test(timeout = 11000)
  public void test1()  throws Throwable  {
      PulseMain pulseMain0 = new PulseMain();
  }

  @Test(timeout = 11000)
  public void test2()  throws Throwable  {
      FileSystemHandling.shouldAllThrowIOExceptions();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Config.txt");
      byte[] byteArray0 = new byte[4];
      FileSystemHandling.appendDataToFile(evoSuiteFile0, byteArray0);
      String[] stringArray0 = new String[1];
      try { 
        PulseMain.main(stringArray0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 11000)
  public void test3()  throws Throwable  {
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Config.txt");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "#~/Z!:3:2d[");
      // Undeclared exception!
      try { 
        PulseMain.main((String[]) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 2
         //
         verifyException("dimacs9.Settings", e);
      }
  }

  @Test(timeout = 11000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[5];
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("Config.txt");
      FileSystemHandling.appendStringToFile(evoSuiteFile0, "r;zR~_,wljN\u0007@TIN\"");
      // Undeclared exception!
      try { 
        PulseMain.main(stringArray0);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }
}
