/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 18 23:19:13 GMT 2022
 */

package dimacs9;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import dimacs9.DukqstraDist;
import dimacs9.DukqstraTime;
import dimacs9.ShortestPathTask;
import org.junit.runner.RunWith;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShortestPathTask_ESTest extends ShortestPathTask_ESTest_scaffolding {

  @Test(timeout = 11000)
  public void test0()  throws Throwable  {
      ShortestPathTask shortestPathTask0 = new ShortestPathTask(13, (DukqstraDist) null, (DukqstraTime) null);
      // Undeclared exception!
      try { 
        shortestPathTask0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dimacs9.ShortestPathTask", e);
      }
  }

  @Test(timeout = 11000)
  public void test1()  throws Throwable  {
      ShortestPathTask shortestPathTask0 = new ShortestPathTask(1, (DukqstraDist) null, (DukqstraTime) null);
      // Undeclared exception!
      try { 
        shortestPathTask0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("dimacs9.ShortestPathTask", e);
      }
  }
}
